### ISSUE TITLE
[Meta] Improve contributor workflow

### ISSUE THREAD

**Issue by ConnorJC3** [UF-ACE/ace-home#7]
- [x] Add linter with standardized config
- [x] Add `.editorconfig` (See https://editorconfig.org/)
- [x] Decide on process for reviewing PRs
- [x] `CODEOWNERS` file(s)?
- [x] Add CI workflow to validate testing tools
- [x] (Only after all above are completed) Disable direct push access on `master` branch
- [x] Move build from quay.io auto-build to Ace Cloud infra
- [x] Audit GitHub user access to this repo
- [x] Add CD to ACE Cloud
- [ ] Update `README.md` and add `CONTRIBUTING.md`

**Comment by ChristopherJMiller** [comment]
For reviewing PRs, I believe we should have a process of requiring multiple reviewers to check off on it (Most likely 2). However, I'm not sure of what tools are available to accomplish this.

**Comment by ConnorJC3** [comment]
@ChristopherJMiller GitHub has a built in system to require reviewers, but an annoying caveat is that you cannot review your own PR on github. Therefore, it is impossible to bypass this requirement in an emergency without modifying the repo settings.

The only alternative reviewing tool I'm aware of is https://reviewable.io/, which is used by the k8s project.

**Comment by ChristopherJMiller** [comment]
@ConnorJC3 I believe I remember us looking at reviewable in the past and it looked good then. I think it would be a good idea to move forward with it.
